name: Keploy API Test

on:
  push:
    branches:
      - main

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Keploy CLI
      run: |
        curl -LO https://github.com/keploy/keploy/releases/latest/download/keploy-linux-amd64
        chmod +x keploy-linux-amd64
        sudo mv keploy-linux-amd64 /usr/local/bin/keploy

    - name: Run Keploy Test
      run: |
        keploy test --url https://books-api-h6um.onrender.com \
                    --schema ./openapi.yaml \
                    --curls ./curls.txt
