name: Keploy API Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  keploy-api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Keploy
        run: |
          curl -LO https://github.com/keploy/keploy/releases/download/v2.6.14/keploy_linux_amd64.tar.gz
          tar -xzf keploy_linux_amd64.tar.gz
          chmod +x keploy
          sudo mv keploy /usr/local/bin/keploy

      - name: Run Keploy Tests
        run: |
          keploy test --url https://books-api-h6um.onrender.com
